version: '3'
services:
    prerender:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
        - 80:80
        environment:
        - MEMORY_CACHE=0
        - CACHE_MAXSIZE=1000
        - CACHE_TTL=6000
        restart: unless-stopped